
name: Rust Security Audi
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}


# jobs:
#   security_audit:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install Rust
#       uses: actions-rs/toolchain@v1
#       with:
#         toolchain: stable
#         profile: minimal
#         override: true

#     - name: Install cargo-audit
#       uses: actions-rs/audit-check@v1
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}

#     - name: Run cargo-audit
#       run: cargo audit